#ifndef ROVERCPP_CONTROLLERLIB_TESTUTILS_HPP_
#define ROVERCPP_CONTROLLERLIB_TESTUTILS_HPP_

#ifdef BUILD_FOR_UNITTEST

#define PRIVATE public
#define PROTECTED public
#endif // BUILD_FOR_UNITTEST

#ifndef BUILD_FOR_UNITTEST
#define PRIVATE private
#define PROTECTED protected
#endif // BUILD_FOR_UNITTEST

#endif // ROVERCPP_CONTROLLERLIB_TESTUTILS_HPP_
